Pizzeria/Pizzeria/Models/Pizza.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Pizzeria.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        public string Nazwa { get; set; }

        public int Cena { get; set; }

        public string Składniki { get; set; }

        public string Photo { get; set; }

        [NotMapped]
        [Range(0, 5, ErrorMessage = "Przykro nam, maksymalnie można zamówić 5 pizz")]
        public int Ilość { get; set; }
    }
}

Pizzeria/Pizzeria/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Pizzeria.Models;

namespace Pizzeria.Controllers
{
    [Authorize(Users = "mpiorek95@gmail.com")]
    public class PizzasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pizzas
        public ActionResult Index()
        {
            return View(db.Pizzas.ToList());
        }

        // GET: Pizzas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizza pizza = db.Pizzas.Find(id);
            if (pizza == null)
            {
                return HttpNotFound();
            }
            return View(pizza);
        }

        // GET: Pizzas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pizzas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nazwa,Cena,Składniki")] Pizza pizza)
        {
            if (ModelState.IsValid)
            {
                db.Pizzas.Add(pizza);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pizza);
        }

        // GET: Pizzas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizza pizza = db.Pizzas.Find(id);
            if (pizza == null)
            {
                return HttpNotFound();
            }
            return View(pizza);
        }

        // POST: Pizzas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nazwa,Cena,Składniki")] Pizza pizza)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pizza).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pizza);
        }

        // GET: Pizzas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizza pizza = db.Pizzas.Find(id);
            if (pizza == null)
            {
                return HttpNotFound();
            }
            return View(pizza);
        }

        // POST: Pizzas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pizza pizza = db.Pizzas.Find(id);
            db.Pizzas.Remove(pizza);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Pizzas/Menu
        [HttpGet]
        public ActionResult Menu()
        {
            return View(db.Pizzas.ToList());
        }

        // POST: Pizzas/Menu
        [HttpPost]
        public ActionResult Menu(FormCollection values)
        {
            if (ModelState.IsValid)
            {
                var iloscistring = values.GetValues("Ilość");
                var ilosci = new List<int>();
                foreach(var x in iloscistring)
                {
                    ilosci.Add(int.Parse(x));
                }

                var pizze = db.Pizzas.ToList();

                for (int i = 0; i < pizze.Count(); i++)
                {

                    pizze[i].Ilość = ilosci[i];
                }

                pizze = pizze.Where(x => x.Ilość > 0).ToList();

                var aUserId = User.Identity.GetUserId();
                var aUser = db.Users.FirstOrDefault(x => x.Id == aUserId);

                var zamowienie = new Order()
                {
                    Pizzas = pizze as ICollection<Pizza>,
                    UserId = aUserId,
                    User = aUser
                };

                zamowienie.GetValue();

                db.Orders.Add(zamowienie);
                db.SaveChanges();
            }

            return View(db.Pizzas.ToList());
        }
    }
}

Pizzeria/Pizzeria/Views/Pizzas/Create.cshtml
@model Pizzeria.Models.Pizza

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pizza</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Składniki, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Składniki, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Składniki, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzeria/Pizzeria/Views/Pizzas/Delete.cshtml
@model Pizzeria.Models.Pizza

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pizza</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Składniki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Składniki)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        <input type="button" class="btn btn-default" value="Back to List" onclick="location.href='@Url.Action("Index", "Pizzas")';return false;"/>
    </div>
    }
</div>

Pizzeria/Pizzeria/Views/Pizzas/Details.cshtml
@model Pizzeria.Models.Pizza

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pizza</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Składniki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Składniki)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            
        </dt>

        <dd>
            <img src="@Url.Content(Model.Photo)" width="230" height="150" alt="Something is no yes" />
        </dd>

    </dl>
</div>
<p>
    <input type="button" class="btn btn-default" value="Edit" onclick="location.href='@Url.Action("Edit", "Pizzas", new { id = Model.Id })';return false;" />
    <input type="button" class="btn btn-default" value="Back to List" onclick="location.href='@Url.Action("Index", "Pizzas")';return false;" />
</p>

Pizzeria/Pizzeria/Views/Pizzas/Edit.cshtml
@model Pizzeria.Models.Pizza

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pizza</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Składniki, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Składniki, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Składniki, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <input type="button" class="btn btn-default" value="Back to List" onclick="location.href='@Url.Action("Index", "Pizzas")';return false;" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzeria/Pizzeria/Views/Pizzas/Index.cshtml
@model IEnumerable<Pizzeria.Models.Pizza>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Składniki)
        </th>
        <th>
            Ilość
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@Url.Content(item.Photo)" width="230" height="150" alt="Something is no yes" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Składniki)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Pizzeria/Pizzeria/Views/Pizzas/Menu.cshtml
@model IEnumerable<Pizzeria.Models.Pizza>

@{
    ViewBag.Title = "Index";
}

<h2>Menu</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="table">
            <tr>
                <th>

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nazwa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cena)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Składniki)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ilość)
                </th>
            </tr>

            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                <img src="@Url.Content(Model.ElementAt(i).Photo)" width="150" height="100" alt="Something is no yes" />
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(model => Model.ElementAt(i).Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model.ElementAt(i).Nazwa, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(model => Model.ElementAt(i).Cena, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model.ElementAt(i).Cena, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(model => Model.ElementAt(i).Składniki, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model.ElementAt(i).Składniki, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.EditorFor(model => Model.ElementAt(i).Ilość, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model.ElementAt(i).Ilość, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zamów" class="btn btn-default" />
            </div>
        </div>

    </div>
}