Pizzeria/Pizzeria/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pizzeria.Models
{
    public class Order
    {
        [Display(Name = "Numer zamówienia")]
        public int Id { get; set; }

        public string UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<Pizza> Pizzas { get; set; }

        [Display(Name = "Kwota zamówienia")]
        public int Value { get; set; }

        public DateTime Data { get; set; }

        public Order()
        {
            Value = 0;
            Data = DateTime.Now;
            Zrealizowane = false;
        }

        public int GetValue()
        {
            foreach (var pizza in Pizzas)
            {
                Value += pizza.Cena * pizza.Ilość;
            }

            return Value;
        }

        public bool Zrealizowane { get; set; }
    }
}

Pizzeria/Pizzeria/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pizzeria.Models
{
    public class OrderViewModel
    {
        public List<Order> Orders = new List<Order>();

        public List<Edge> Edges = new List<Edge>();
    }
}

Pizzeria/Pizzeria/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json.Linq;
using Pizzeria.Models;
using Pizzeria.Services;

namespace Pizzeria.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private OrderService service;
        private string pizzeria = "Politechnika Wrocławska";

        // GET: Orders
        public ActionResult Index()
        {
            return View(db.Orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Value,Data")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Value,Data")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Orders
        public ActionResult Harmonogram()
        {
            service = new OrderService();

            var Zamówienia = db.Orders.Where(x => x.Zrealizowane == false).ToList();

            service.OrganizeOrdersPwr(Zamówienia);

            return View(service.owm);
        }

        public string Seed()
        {
            var UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

            var pizze = db.Pizzas.ToList() as ICollection<Pizza>;
            var users = db.Users.ToList();

            var iter = 4;//users.Count();

            for(int i=0; i<iter; i++)
            {
                var pizza = pizze.First();
                pizza.Ilość = 1;
                var listpizza = new List<Pizza> { pizza };
                var user = users.First();
                var id = user.Id;

                var zamowienie = new Order()
                {
                    Pizzas = listpizza as ICollection<Pizza>,
                    UserId = id,
                    User = user
                };

                zamowienie.GetValue();

                db.Orders.Add(zamowienie);

                pizze.Remove(pizza);
                users.Remove(user);
            }

            db.SaveChanges();

            return "OK";
        }

    }
}

Pizzeria/Pizzeria/Views/Orders/Create.cshtml
@model Pizzeria.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzeria/Pizzeria/Views/Orders/Delete.cshtml
@model Pizzeria.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Pizzeria/Pizzeria/Views/Orders/Details.cshtml
@model Pizzeria.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Pizzeria/Pizzeria/Views/Orders/Edit.cshtml
@model Pizzeria.Models.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        <input type="button" class="btn btn-default" value="Back to List" onclick="location.href='@Url.Action("Index", "Orders")';return false;" />
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzeria/Pizzeria/Views/Orders/Harmonogram.cshtml
@model Pizzeria.Models.OrderViewModel

@{
    ViewBag.Title = "Harmonogram";
}

<h2>Harmonogram dostaw</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Orders[0].Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Orders[0].User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Orders[0].Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Orders[0].Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Orders[0].User.Adres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edges[0].Distance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edges[0].Time)
        </th>
        <th></th>
    </tr>

    @for (int i=0; i< Model.Orders.Count(); i++)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.Orders[i].Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Orders[i].User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Orders[i].Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Orders[i].Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Orders[i].User.Adres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Edges[i].Distance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Edges[i].Time)
        </td>
    </tr>
    }

</table>

Pizzeria/Pizzeria/Views/Orders/Index.cshtml
@model IEnumerable<Pizzeria.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Adres)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Adres)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>